[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Sébastien Eustace <sebastien@eustace.io>"]

[tool.poetry.dependencies]
python = ">=3.8"
click = "^8.1.2"
pytest-coverage = "^0.0"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
flake8 = "^4.0.1"
black = "^22.3.0"
